// <auto-generated />
using System;
using Itsm.Api;
using Itsm.Common.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Itsm.Api.Migrations
{
    [DbContext(typeof(ItsmDbContext))]
    partial class ItsmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Itsm.Api.ComputerRecord", b =>
                {
                    b.Property<string>("ComputerName")
                        .HasColumnType("text");

                    b.Property<Computer>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ComputerName");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("Itsm.Api.DiskUsageRecord", b =>
                {
                    b.Property<string>("ComputerName")
                        .HasColumnType("text");

                    b.Property<DiskUsageSnapshot>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("ScannedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ComputerName");

                    b.ToTable("DiskUsageSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
